# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'task_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12task_service.proto\"?\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\"\x1e\n\x0cTaskResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"8\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_name\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\"4\n\x11TaskResultRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\";\n\x18TaskCompleteNotification\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xb2\x01\n\x0bTaskService\x12&\n\x07RunTask\x12\x0c.TaskRequest\x1a\r.TaskResponse\x12\x18\n\x07GetTask\x12\x06.Empty\x1a\x05.Task\x12(\n\nTaskResult\x12\x12.TaskResultRequest\x1a\x06.Empty\x12\x37\n\rGetTaskResult\x12\x12.TaskResultRequest\x1a\x12.TaskResultRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=22
  _globals['_TASKREQUEST']._serialized_end=85
  _globals['_TASKRESPONSE']._serialized_start=87
  _globals['_TASKRESPONSE']._serialized_end=117
  _globals['_TASK']._serialized_start=119
  _globals['_TASK']._serialized_end=175
  _globals['_TASKRESULTREQUEST']._serialized_start=177
  _globals['_TASKRESULTREQUEST']._serialized_end=229
  _globals['_TASKCOMPLETENOTIFICATION']._serialized_start=231
  _globals['_TASKCOMPLETENOTIFICATION']._serialized_end=290
  _globals['_EMPTY']._serialized_start=292
  _globals['_EMPTY']._serialized_end=299
  _globals['_TASKSERVICE']._serialized_start=302
  _globals['_TASKSERVICE']._serialized_end=480
# @@protoc_insertion_point(module_scope)
